# Generated by Django 4.2.2 on 2023-07-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='activiteClient',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='clientPresume',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='gerantClient',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='mereClient',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='numRegistreCommerceClient',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='pereClient',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='professionClient',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='dateFermetureCompte',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='dateMiseEnOpposition',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='soldeCourant',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='soldeHier',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='libelleTransaction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
