# Generated by Django 4.2.2 on 2023-07-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0002_alter_clients_activiteclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='nbrModifInfoClient',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='soldeCourant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='soldeHier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='montantMouvement',
            field=models.PositiveIntegerField(),
        ),
    ]
