# Generated by Django 4.2.2 on 2023-07-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0005_alter_clients_preclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='preClient',
            field=models.CharField(max_length=30),
        ),
    ]
