# Generated by Django 4.2.2 on 2023-07-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0007_utilisateurs_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='mdpUtil',
            new_name='password',
        ),
    ]
