# Generated by Django 4.2.2 on 2023-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0009_utilisateurs_groups_utilisateurs_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='codeClient',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='numeroCompte',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='numMouvement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='idUtil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
