# Generated by Django 4.2.2 on 2023-07-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0010_alter_clients_codeclient_alter_comptes_numerocompte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='UtilSusp',
            field=models.BooleanField(default=False),
        ),
    ]
