# Generated by Django 4.2.2 on 2023-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0011_alter_utilisateurs_utilsusp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='dateCreUtil',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='dateDernOperUtil',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='heureCreUtil',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='nivUtil',
            field=models.IntegerField(choices=[(0, 'Simple'), (1, 'Administrateur')], null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='serviceUtil',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
