# Generated by Django 4.2.2 on 2023-07-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0012_alter_utilisateurs_datecreutil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='dateDernOperUtil',
            new_name='derniereOperUtil',
        ),
    ]
