# Generated by Django 4.2.2 on 2023-07-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0016_alter_clients_activiteclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='adresse2Client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='situationFamiliale',
            field=models.IntegerField(blank=True, choices=[(0, 'Célébataire'), (1, 'Marié(e)')], null=True),
        ),
    ]
