# Generated by Django 4.2.2 on 2023-07-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0019_alter_mouvements_gl_alter_mouvements_utilvalid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together={('codeAgenceClient', 'idClient')},
        ),
    ]
