# Generated by Django 4.2.2 on 2023-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0020_alter_clients_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='nbrModifInfoClient',
            field=models.PositiveBigIntegerField(),
        ),
    ]
