# Generated by Django 4.2.2 on 2023-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0022_alter_clients_pieceidentclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='situationFamiliale',
            field=models.IntegerField(blank=True, choices=[(0, 'Célibataire'), (1, 'Marié(e)')], null=True),
        ),
    ]
