# Generated by Django 4.2.2 on 2023-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveApp', '0024_alter_grandlivres_libellegl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvements',
            name='RIB',
            field=models.CharField(max_length=200),
        ),
    ]
