# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import flowApp

username = ""
url = 'http://localhost:8000/moveApp/'

class Ui_Form(object):
    def openFlowAppWindow(self, username):
        self.window = QtWidgets.QMainWindow()
        self.ui = flowApp.FlowInterface(username)
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(825, 574)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.Holder = QtWidgets.QWidget(Form)
        self.Holder.setGeometry(QtCore.QRect(2, 2, 820, 570))
        self.Holder.setStyleSheet("QPushButton#loginButton{\n"
"    background-color: rgba(142, 141, 142, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#loginButton:hover{\n"
"    background-color: rgb(235, 28, 39);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#loginButton:pressed{\n"
"    background-color:  rgba(142, 141, 142, 1);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exitButton{\n"
"    background-color: rgba(255, 255, 255, 0)\n"
"}")
        self.Holder.setObjectName("Holder")
        self.right = QtWidgets.QLabel(self.Holder)
        self.right.setGeometry(QtCore.QRect(400, 40, 421, 481))
        self.right.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.right.setText("")
        self.right.setObjectName("right")
        self.left = QtWidgets.QLabel(self.Holder)
        self.left.setGeometry(QtCore.QRect(0, 0, 410, 570))
        self.left.setStyleSheet("background-color: rgb(235, 28, 39);\n"
"image: url(:/images/Ressources/Images/background.png);\n"
"border-radius: 20px;\n"
"")
        self.left.setText("")
        self.left.setObjectName("left")
        self.loginLabel = QtWidgets.QLabel(self.Holder)
        self.loginLabel.setGeometry(QtCore.QRect(520, 130, 190, 51))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.Holder)
        self.welcomeLabel.setGeometry(QtCore.QRect(10, 46, 190, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.aLabel = QtWidgets.QLabel(self.Holder)
        self.aLabel.setGeometry(QtCore.QRect(100, 118, 190, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.aLabel.setFont(font)
        self.aLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.aLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aLabel.setObjectName("aLabel")
        self.logo = QtWidgets.QLabel(self.Holder)
        self.logo.setGeometry(QtCore.QRect(546, 60, 141, 71))
        self.logo.setStyleSheet("image: url(:/images/Ressources/Images/CNEP_FLOW.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.flowLabel = QtWidgets.QLabel(self.Holder)
        self.flowLabel.setGeometry(QtCore.QRect(207, 190, 190, 81))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.flowLabel.setFont(font)
        self.flowLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.flowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.flowLabel.setObjectName("flowLabel")
        self.usernameInput = QtWidgets.QLineEdit(self.Holder)
        self.usernameInput.setGeometry(QtCore.QRect(490, 260, 251, 35))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(12)
        self.usernameInput.setFont(font)
        self.usernameInput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1.5px solid rgb(142, 141, 142);\n"
"border-radius: 8px;\n"
"padding: 3px;")
        self.usernameInput.setText("")
        self.usernameInput.setPlaceholderText("")
        self.usernameInput.setObjectName("usernameInput")
        self.usernameLabel = QtWidgets.QLabel(self.Holder)
        self.usernameLabel.setGeometry(QtCore.QRect(554, 230, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordInput = QtWidgets.QLineEdit(self.Holder)
        self.passwordInput.setGeometry(QtCore.QRect(490, 340, 251, 35))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(12)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1.5px solid rgb(142, 141, 142);\n"
"border-radius: 8px;\n"
"padding: 3px;")
        self.passwordInput.setText("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.passwordLabel = QtWidgets.QLabel(self.Holder)
        self.passwordLabel.setGeometry(QtCore.QRect(559, 310, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.loginButton = QtWidgets.QPushButton(self.Holder)
        self.loginButton.setGeometry(QtCore.QRect(552, 410, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("")
        self.loginButton.setObjectName("loginButton")
        self.exitButton = QtWidgets.QPushButton(self.Holder)
        self.exitButton.setGeometry(QtCore.QRect(780, 50, 31, 41))
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Ressources/Images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(20, 20))
        self.exitButton.setObjectName("exitButton")
        self.errorMessage = QtWidgets.QLabel(self.Holder)
        self.errorMessage.setGeometry(QtCore.QRect(426, 470, 381, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(12)
        self.errorMessage.setFont(font)
        self.errorMessage.setStyleSheet("color: rgb(235, 28, 39);")
        self.errorMessage.setText("")
        self.errorMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.errorMessage.setObjectName("errorMessage")
        self.right.raise_()
        self.left.raise_()
        self.loginLabel.raise_()
        self.logo.raise_()
        self.usernameInput.raise_()
        self.usernameLabel.raise_()
        self.passwordInput.raise_()
        self.passwordLabel.raise_()
        self.loginButton.raise_()
        self.exitButton.raise_()
        self.welcomeLabel.raise_()
        self.flowLabel.raise_()
        self.aLabel.raise_()
        self.errorMessage.raise_()
        self.left.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.right.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.loginButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))

        self.retranslateUi(Form)
        self.exitButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

        #Connections
        self.loginButton.clicked.connect(lambda: self.login(Form))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loginLabel.setText(_translate("Form", "Se connecter"))
        self.welcomeLabel.setText(_translate("Form", "Bienvenue"))
        self.aLabel.setText(_translate("Form", "à"))
        self.flowLabel.setText(_translate("Form", "FLOW"))
        self.usernameLabel.setText(_translate("Form", "Nom d\'utilisateur"))
        self.passwordLabel.setText(_translate("Form", "Mot de passe"))
        self.loginButton.setText(_translate("Form", "Se connecter"))

    def login(self, Form):
        username = self.usernameInput.text()
        password = self.passwordInput.text()

        # Send login request to the server
        data={'username': username, 'password': password}
        response = requests.post(url + 'login/', data=data)

        # Handle the response
        if response.status_code == 200:
            response_data = response.json()
            if response_data.get('success'):
                # Login successful, perform necessary actions
                self.errorMessage.setText("Connecté(e). Chargement ...")
                Form.close()
                self.openFlowAppWindow(username)
            else:
                error_message = response_data.get('message')
                self.errorMessage.setText(error_message)
        else:
            self.errorMessage.setText('Erreur lors de la connexion.')
import res_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
